[package]
name                   = "harmion-connect"
version.workspace      = true
authors.workspace      = true
edition.workspace      = true
license.workspace      = true
repository.workspace   = true
rust-version.workspace = true

[dependencies]
serde = "1.0.219"

webrtc = "0.13.0"

thiserror = "2.0.12"
tracing   = "0.1.41"
